# This is a basic workflow to help you get started with Actions

name: Build and Upload Exe

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -name: Set up Python
      -uses: actions/setup-python@v2
      with:
        python-version: '3.x'

      # Runs a single command using the runners shell
      -name: Install dependencies
        run: |
           pip install pyinstaller

      # Runs a set of commands using the runners shell
      - name: Build project
        run: |
          pyinstaller --onefile code.py
          pyinstaller --onefile json1.py
          pyinstaller --onefile json2.py
          pyinstaller --onefile yml1.py
          pyinstaller --onefile yml2.py
          pyinstaller --onefile xml1.py
          pyinstaller --onefile xml2.py

      - name: Upload Task1 artifact
  uses: actions/upload-artifact@v2
  with:
    name: Task1
    path: project/Task1

    - name: Upload Task2 artifact
  uses: actions/upload-artifact@v2
  with:
    name: Task2
    path: project/Task2

    - name: Upload Task3 artifact
  uses: actions/upload-artifact@v2
  with:
    name: Task3
    path: project/Task3

    - name: Upload Task4 artifact
  uses: actions/upload-artifact@v2
  with:
    name: Task4
    path: project/Task4

    - name: Upload Task5 artifact
  uses: actions/upload-artifact@v2
  with:
    name: Task5
    path: project/Task5

    - name: Upload Task6 artifact
  uses: actions/upload-artifact@v2
  with:
    name: Task6
    path: project/Task6

    - name: Upload Task7 artifact
  uses: actions/upload-artifact@v2
  with:
    name: Task7
    path: project/Task7
    
